### ISSUE TITLE
Suggestions to improve README.md

### ISSUE THREAD

**Issue by ThomasLandauer** [core23/DompdfBundle#13]
## Feature Request

* What can `$options` be in `streamHtml()` and `getPdf()`? Example?
* "Enable the Bundle" is not necessary if you use Symfony 4 *or* Flex - I'm not sure which it is :-)
* Which other defaults can be configured in `core23_dompdf.yaml`?
* How can you add meta data (without the bundle it's: `$dompdf->add_info('Title', $title);`)

I can't create additional PR's, since I don't know the answers ;-)

**Comment by reyostallenberg** [comment]
> How can you add meta data (without the bundle it's: $dompdf->add_info('Title', $title);)

Could be accomplished with the proposal of https://github.com/core23/DompdfBundle/issues/15 implemented

**Comment by core23** [comment]
Feel free to improve the `README.md` file @ThomasLandauer
