### ISSUE TITLE
Dispatch event before streaming or outputting

### ISSUE THREAD

**Issue by reyostallenberg** [core23/DompdfBundle#15]
## Feature Request

It would be great to have events (for example a [Generic Event Object](https://symfony.com/doc/current/components/event_dispatcher/generic_event.html)) dispatched before these lines:
- https://github.com/core23/DompdfBundle/blob/bfd9c1ca389a7ee6f56fff3511bf824d63bd35ff/src/Wrapper/DompdfWrapper.php#L39
- https://github.com/core23/DompdfBundle/blob/bfd9c1ca389a7ee6f56fff3511bf824d63bd35ff/src/Wrapper/DompdfWrapper.php#L51

With as event subject the `$pdf` variable. In that way a programmer can for example get the DomPDF canvas to do some modifications at the end that always need to be done.

An example implementation could be:
```php
// require symfony/event-dispatcher
// inject the event dispatcher
// create Core23\DompdfBundle\Events class with suitable constants

// DompdfWrapper::streamHtml
$event = new \Symfony\Component\EventDispatcher\GenericEvent($pdf);
$this->dispatcher->dispatch(\Core23\DompdfBundle\Events::STREAM, $event);
$event->getSubject()->stream($filename);

// DompdfWrapper::getPdf
$event = new \Symfony\Component\EventDispatcher\GenericEvent($pdf);
$this->dispatcher->dispatch(\Core23\DompdfBundle\Events::OUTPUT, $event);
$event->getSubject()->output();
```

**Comment by core23** [comment]
Can you provide a PR please @reyostallenberg ?

**Comment by reyostallenberg** [comment]
I can and will of you are okay with the event dispatcher as additional
dependency

**Comment by core23** [comment]
Maybe you can find a way to make the event dispatcher optional or find some other hooks
