### ISSUE TITLE
Pdf output to the browser doesn't work

### ISSUE THREAD

**Issue by tgeber** [core23/DompdfBundle#17]
In the class ```Core23\DompdfBundle\Wrapper\DompdfWrapper``` exists the method ```streamHtml```, which takes an ```options``` array as the third parameter. This options are not proceeded to the underlaying ```stream```-method of the ```dompdf``` class. So in the ```stream```-method of the used adapter-class, the options passed by the creation of dompdf instance, will allways been overwritten with the default values set in this method. Therfore it's impossible to stream the pdf to the browser.

**Comment by core23** [comment]
Can you provide a fix please @tgeber ?

**Comment by tgeber** [comment]
@core23 Yes, I will do it tomorrow.
Best regards from germany.
