### ISSUE TITLE
ServiceNotFoundException / Dependency Injection

### ISSUE THREAD

**Issue by ThomasLandauer** [core23/DompdfBundle#24]
### Environment

DEV

#### PHP version

7.2
Symfony 3.4.17, Symfony Flex

## Subject

Service not found with `$this->get('dompdf');` in a Controller.

## Actual results

> Service "dompdf" not found: even though it exists in the app's container, the container inside "App\Controller\MyController" is a smaller service locator that only knows about the "doctrine", "form.factory", "http_kernel", "request_stack", "router", "session", "templating" and "twig" services. Unless you need extra laziness, try using dependency injection instead. Otherwise, you need to declare it using "MyController::getSubscribedServices()".

**Comment by ThomasLandauer** [comment]
This is 2.4.0 already.

**Comment by prodigeris** [comment]
Use dependency injection.

**Comment by bobman38** [comment]
Just for the next one coming on this case, use this in your controller:

```
use Core23\DompdfBundle\Wrapper\DompdfWrapper;

class MyController extends AbstractController {
    /**
     * @Route("/myroute", name="myroute")
     */
    public function action(DompdfWrapper $dompdf) {
      $html = $this->renderView('view.html.twig', [
      ]);

      $response = $dompdf->getStreamResponse($html, "file");
      $response->send();
    }
}
```

**Comment by core23** [comment]
Getting the service using the service registry is deprecated, sorry
