### ISSUE TITLE
Question about twig asset() when rendering pdf using twig

### ISSUE THREAD

**Issue by fd6130** [core23/DompdfBundle#243]
## Question

Hi, i'm not sure what is the issue but i have to use absolute path for images and css because `{{ asset() }}` isn't working when rendering the pdf from twig.

Is this normal when rendering pdf from twig? Thanks.

**Comment by fd6130** [comment]
Or it is because i didn't set the `chroot` correctly?

**Comment by core23** [comment]
This is an issue of https://github.com/dompdf/dompdf/issues/2229

> Or it is because i didn't set the `chroot` correctly?

This should solve the issue

**Comment by fd6130** [comment]
> This is an issue of [dompdf/dompdf#2229](https://github.com/dompdf/dompdf/issues/2229)
> 
> > Or it is because i didn't set the `chroot` correctly?
> 
> This should solve the issue

This is the default yaml configuration from this bundle:

```
nucleos_dompdf:
    defaults:
        chroot: '%kernel.project_dir%/public/assets'
```

And when i try to render the image from `/public/assets` using `{{ asset('assets/some-image.jpg') }}` it give me `Image not found or type unknown` error.

**Comment by fd6130** [comment]
Ok seems like have to enable `isRemoteEnabled: true` and use `{{ absolute_url( asset() ) }}` instead.

**Comment by core23** [comment]
Can you add a short note to the README @fd6130 ?

**Comment by fd6130** [comment]
> Can you add a short note to the README @fd6130 ?

Sure, i will create a PR later.
