### ISSUE TITLE
function streamHtml is deprecated, use getStreamResponse instead

### ISSUE THREAD

**Issue by fd6130** [core23/DompdfBundle#373]
## Question

When i inject DompdfWrapperInterface into my code, my vscode IDE keep telling me undefine method of `getStreamResponse()`. When i look into the interface, the comment above the`streamHtml()` said use `getStreamResponse() instead` but i don't see the method define in the interface but in DompdfWrapper class instead. 

How about adding `getStreamResponse()` into the interface to remove the IDE warning? Or we can just inject DompdfWrapper instead of an Interface, perhaps the docs need to update as well?

**Comment by core23** [comment]
Already done on the major branch: https://github.com/nucleos/NucleosDompdfBundle/pull/172

**Comment by fd6130** [comment]
> Already done on the major branch: #172

Since adding a new method in to the interface is a major change and we are not sure when is the next major version will be release. How about adding this to the comment of the interface instead?

```
/**
 * @method StreamedResponse getStreamResponse(string $html, string $filename, array $options = [])
 */
interface DompdfWrapperInterface
{

}
```
This should help to solve the IDE warning until next major version release. How do you think?

**Comment by core23** [comment]
Can you do this @fd6130 ?

**Comment by fd6130** [comment]
> Can you do this @fd6130 ?

Yes i can. Later i will submit a PR for this case. Which branch should i commit to? 3.1.x or 3.2.x?

**Comment by core23** [comment]
You can target the 3.2.x branch. The 3.1.x branch is for (security) bugfixes only.
