### ISSUE TITLE
Bundle does not configure temp and cache paths

### ISSUE THREAD

**Issue by willemstuursma** [core23/DompdfBundle#7]
I expected the bundle to set the temp and cache paths of DomPDF to Symfony's paths. However, it does not.

This would be very useful as that means that I don't have to reconfigure DomPDF.

**Comment by core23** [comment]
Can you provide a Pull Request with a fix? @willemstuursma

**Comment by willemstuursma** [comment]
I'm sorry, I'm quite new to the Symfony game and I don't know how to access `%kernel.cache_dir%` from the Factory, if you can help me with that I can create a PR.

**Comment by core23** [comment]
Caching is an experimental feature:
https://github.com/dompdf/dompdf/blob/master/src/Dompdf.php#L661-L665

Which temp path are you missing for dompdf?

**Comment by willemstuursma** [comment]
The font cache: https://github.com/dompdf/dompdf/blob/master/src/Options.php#L772

**Comment by core23** [comment]
https://github.com/core23/DompdfBundle/releases/tag/2.1.0

**Comment by willemstuursma** [comment]
Thanks!
