### ISSUE TITLE
Image not found or type unknown

### ISSUE THREAD

**Issue by DarKFlameS** [core23/DompdfBundle#9]
I'm trying to render my template into a PDF file, but images are not rendered, it always appears the msg "Image not found or type unknown". I've already tried with relative and absolute image paths. It's a jpg image.

Can you help me with it?

**Comment by core23** [comment]
Can you please post some example code? 

Have you checked if this is a general [dompdf](https://github.com/dompdf/dompdf) problem or a bundle problem?

**Comment by DarKFlameS** [comment]
Sorry, forgot to post back here. I've set all my images to use absolute path and added the remote option in the code (in the config file was not working).
 something like

`
$html = $this->renderView('myview.html.twig', $data);
$dompdf = $this->get('dompdf');
$response = new Response();
$response->setContent($dompdf->streamHtml($html, 'myfile.pdf', ['isRemoteEnabled' => TRUE]));
$response->setStatusCode(200);
$response->headers->set('Content-type', 'application/pdf');
return $response;
`

that solved my problem

**Comment by rk8585985963-art** [comment]
Image not found or type unknown
